---
- hosts: all
  become: true
  tasks:
    - name: install apache(httpd)
      yum:
        name: httpd
	      state: latest

    - name: start apache
      service:
        name: httpd
        state: start
    - name: copy index.html file
      copy:
        src: index.html
        dest: /var/www/html/