---
- name: demo on just print a message
  hosts: all
  vars:
    URL: play.cricket.com
    PROJECT: cricket  
  tasks:
    - name: print url
      debug:
        msg: url = {{URL}}
    - name: print url from task
      debug:
        msg: url = {{URL}}
      vars:
        URL: ipl suspended by due to corona.com
- name: demo on dyanamic vars
  hosts: all
  tasks:
    - name: gather date
      shell: date +%F
      register: out
    - name: print date
      debug:
      debug:
        msg: date = {{out.stdout}} 
    - name: set a fact
      set_fact:
        DATE: "{{DATE}}"   