- name: Install dependencies
  apt:
    name: npm
    update_cache: yes
    state: present

- name: Download frontend from Nexus
  get_url:
    url: http://10.1.2.210:8081/repository/Todo/Todo-0.0.1.zip
    dest: /root/todo.zip
    username: admin
    password: admin

- name: Unzip the Downloaded Content
  unarchive:
    src: /root/todo.zip
    dest: /root
    remote_src: yes

- name: Copy todo.Service file
  copy:
    src: /root/todo.service
    dest: /etc/systemd/system/todo.service
    remote_src: yes

- name: Start todos Service
  systemd:
    name: todo
    daemon_reload: yes
    state: started
    enabled: yes