- name: Install dependencies
  apt:
    name: "{{packages}}"
    update_cache: yes
    state: present

- name: Install Nginx
  apt:
    name: nginx
    update_cache: yes
    state: present

- name: start nginx
  systemd:
    state: started
    name: nginx
    enabled: yes

- name: install nodejs
  apt: name=nodejs

- name: Install npm
  apt:
    name: npm 
    update_cache: yes
    state: present
           
- name: Download frontend from nexus
  get_url:
    url: http://10.1.2.210:8081/repository/frontend-todo/frontend-todo-1.0.1.zip
    dest: /root/frontend-todo.zip
    username: admin
    password: admin 

- name: Install npm
  npm:
    name: npm
    global: true

- name: Unzip the download content
  unarchive:
    src: /root/frontend-todo.zip
    dest: /root/
    remote_src: yes

- name: Replace content
  replace:
    path: /etc/nginx/sites-available/default
    regexp: '/var/www/html'
    replace: '/root/frontend/dist'    

- name: start nginx
  service:
     name: nginx
     state: restarted
     name: nginx
     enabled: yes
- name: Replace content
  replace:
    path: /root/config/index.js
    regexp: '127.0.0.1'
    replace: 'login.sasendereddy.ml'

- name: Replace content
  replace:
    path: /root/config/index.js
    regexp: '127.0.0.2'
    replace: 'todo.sasendereddy.ml'

- name: To start npm
  shell: npm start
  args:
    chdir: /root/

