- name: Install dependencies
  apt:
    name: "{{packages}}"
    update_cache: yes
    state: present

- name: Download frontend from Nexus
  get_url:
    url: http://10.1.2.210:8081/repository/user/user-0.0.3.zip
    dest: /root/users.zip
    username: admin
    password: admin

- name: Unzip the Downloaded Content
  unarchive:
    src: /root/users.zip
    dest: /root/
    remote_src: yes


- name: Copy users.Service file
  copy:
    src: users.service
    dest: /etc/systemd/system/users.service
    remote_src: yes

- name: Start users Service
  systemd:
    name: "users"
    daemon_reload: yes
    state: started
    enabled: yes